In [ ]:
#!/usr/bin/env python
# coding: utf-8

In[1]:

In [ ]:
import pandas as pd

In[2]:

In [ ]:
data=pd.read_csv('dataset session 7 Pandas nba.csv')
data.head(3)

In[3]:

In [ ]:
data.tail(3)

In[4]:

In [ ]:
data.dropna()

In[5]:

In [ ]:
data.dropna(how = "all")

In[7]:

In [ ]:
data

In[8]:

In [ ]:
data.dropna(how = "all",inplace=True)

In[9]:

In [ ]:
data.tail(3)

In[10]:

In [ ]:
data.dropna(axis=1)

In[11]:

In [ ]:
data.dropna(axis=1)

In[12]:

In [ ]:
data.dropna(axis="columns")

In[13]:

In [ ]:
data.head(3)

In[14]:

In [ ]:
data.dropna(subset=["Salary","College"])

In[15]:

In [ ]:
nb=data=pd.read_csv('dataset session 7 Pandas nba.csv')
nb.head(3)

In[16]:

In [ ]:
nb.fillna(0)

In[17]:

In [ ]:
nb["Salary"]

In[18]:

In [ ]:
nb["Salary"].fillna(0,inplace=True)

In[19]:

In [ ]:
nb.head()

In[20]:

In [ ]:
nb["College"]

In[21]:

In [ ]:
nb["College"].fillna("No College",inplace=True)

In[22]:

In [ ]:
nb

In[23]:

In [ ]:
n=pd.read_csv('dataset session 7 Pandas nba.csv').dropna(how="all")
n.head(3)

In[24]:

In [ ]:
n.tail(3)

In[25]:

In [ ]:
n["Salary"].fillna(0,inplace=True)

In[28]:

In [ ]:
n

In[29]:

In [ ]:
n["College"].fillna("None",inplace=True)

In[30]:

In [ ]:
n.head(6)

In[31]:

In [ ]:
n.dtypes

In[32]:

In [ ]:
n.info()

In[35]:

In [ ]:
n["Salary"]

In[34]:

In [ ]:
n["Salary"].astype("int")

In[ ]:

In[37]:

In [ ]:
n["Salary"]=n["Salary"].astype("int")

In[38]:

In [ ]:
n.head(3)

In[39]:

In [ ]:
n.info()

In[41]:

In [ ]:
n["Number"].astype("int")

In[42]:

In [ ]:
n["Number"]=n["Number"].astype("int")

In[43]:

In [ ]:
n["Age"].astype("int")

In[44]:

In [ ]:
n["Age"]=n["Age"].astype("int")

In[45]:

In [ ]:
n["Age"].nunique()

In[46]:

In [ ]:
n["Position"].nunique()

In[47]:

In [ ]:
n["Position"].astype("category")

In[48]:

In [ ]:
n["Position"]=n["Position"].astype("category")

In[49]:

In [ ]:
n.info()

In[50]:

In [ ]:
n["Team"].astype("category")

In[51]:

In [ ]:
n["Team"]=n["Team"].astype("category")

In[52]:

In [ ]:
n.info()

In[ ]: